- name: "put /etc/sudoers.d/{{ sudo_user_name }}"
  template:
    src: etc/sudoers.d/user_sudo
    dest: "/etc/sudoers.d/{{ sudo_user_name }}"
    owner: root
    group: root
    mode: 0440
    backup: true
